
const braceletImgs={
     blackChakraImg2 : 'bracelets-imgs/black-chakra/7-chakra-bracelet-low.jpg',
     blackChakraImg1 : 'bracelets-imgs/black-chakra/chakra-bracelet-low.jpg',
     bohoBangleImg1 : 'bracelets-imgs/boho-bangle/bangle-bracelet-with-feathers-low.jpg',
     bohoBangleImg2 : 'bracelets-imgs/boho-bangle/boho-bangle-bracelet-low.jpg',
     buddhaImg1 : 'bracelets-imgs/buddha/black-buddha-bracelet-low.jpg',
     buddhaImg2 : 'bracelets-imgs/buddha/buddha-bracelet-for-men-low.jpg',
     colorChakraImg2 : 'bracelets-imgs/color-chakra/chakra-bracelet-on-marble-low.jpg',
     colorChakraImg1 : 'bracelets-imgs/color-chakra/chakra-bracelet-product-shot-low.jpg',
     embroidImg1 : 'bracelets-imgs/embroidered/embroidered-bracelet-low.jpg',
     goldArrowImg1 : 'bracelets-imgs/gold-arrow/gold-arrow-bracelet-low.jpg',
     jewelsImg1 : 'bracelets-imgs/jewels/bangle-bracelet-with-jewels-low.jpg',
     moonImg1 : 'bracelets-imgs/moon/moon-friendship-bracelet-low.jpg',
     nauticalCharmImg1 : 'bracelets-imgs/nautical-charm/anchor-bracelet-gold-low.jpg',
     nauticalCharmImg2 : 'bracelets-imgs/nautical-charm/nautical-charm-bracelet-low.jpg',
     navyAnchorImg1 : 'bracelets-imgs/navy-anchor/anchor-bracelet-mens-low.jpg',
     navyChakraImg2 : 'bracelets-imgs/navy-chakra/chakra-balancing-bracelet-low.jpg',
     navyChakraImg1 : 'bracelets-imgs/navy-chakra/navy-blue-chakra-bracelet-low.jpg',
     patternBangleImg1 : 'bracelets-imgs/patterned-bangle/patterned-bangle-low.jpg',
     purpleChakraImg1 : 'bracelets-imgs/purple-chakra/chakra-bracelet-for-women-low.jpg',
     purpleChakraImg2 : 'bracelets-imgs/purple-chakra/purple-chakra-bracelet-low.jpg',
     redAnchorImg1 : 'bracelets-imgs/red-anchor/womens-anchor-bracelet-low.jpg',
     simpleGoldImg1 : 'bracelets-imgs/simple-gold/simple-gold-bracelet-low.jpg',
     stackedArrowImg1 : 'bracelets-imgs/stacked-arrow/stacked-bracelets-low.jpg',
     stackedTasselImg1 : 'bracelets-imgs/stacked-tassle/stacked-bracelets-set-low.jpg',
     sunImg1 : 'bracelets-imgs/sun/sun-friendship-bracelet-low.jpg',
}

export default braceletImgs